### ISSUE TITLE
Licence Definition

### ISSUE THREAD

**Issue by pgassmann** [markuman/hetzner_dns#2]
In the manifest file `galaxy.yml`, the license is defined as `"GPL-3.0-or-later"`

It would be good to add a LICENSE or COPYING file and mention the license in the readme and optimally also in the file header like hetzner does with their official modules: https://github.com/ansible-collections/hetzner.hcloud/blob/main/plugins/modules/hcloud_certificate.py

**Comment by markuman** [comment]
Thx. I've added COPYING and the information in head of .py files.

1.2.0 is released.  
* https://github.com/markuman/hetzner_dns/releases/tag/1.2.0
